<!--
GENERATED FILE - DO NOT EDIT
This file was generated by [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets).
Source File: /doc/mdsource/TestingExceptions.source.md
To change this file edit the source file and then execute ./run_markdown_templates.sh.
-->

<a id="top"></a>

# Testing Exceptions

<!-- toc -->
## Contents

  * [Testing exception messages](#testing-exception-messages)
<!-- endtoc -->




## Testing exception messages

Testing exceptions with Approval Tests is very easy. Simply pass in a call to the function (usually wrapped in a lambda). Approval tests will execute the code, catch the exception, and verify the exception's message, i.e. `exception.what()`.

The exception thrown must inherit `std::exception`.

<!-- snippet: verify_exception_message_example -->
<a id='snippet-verify_exception_message_example'/></a>
```cpp
Approvals::verifyExceptionMessage([](){/* your code goes here */});
```
<sup>[snippet source](/tests/Catch2_Tests/ApprovalsTests.cpp#L108-L110) / [anchor](#snippet-verify_exception_message_example)</sup>
<!-- endsnippet -->

---

[Back to User Guide](/doc/README.md#top)
